### ISSUE TITLE
Website gnocchi.xyz is offline

### ISSUE THREAD

**Issue by MichaelEischer** [gnocchixyz/gnocchi#1048]
### How to reproduce your problem
Navigate to http://gnocchi.xyz .

### What is the result that you get
Browser reports "Website not found".

### What is result that you expected
The website / documentation should be shown.

Note: `dig @8.8.8.8 gnocchi.xyz` returns no IP address for the domain.

**Comment by jd** [comment]
The domain has expired.

**Comment by cpl** [comment]
Are there any plans of renewing the domain or hosting/providing the documentation somewhere else?

**Comment by cpl** [comment]
Guess this works for now:
https://web.archive.org/web/20190119150122/http://gnocchi.xyz/

But come on ...

**Comment by sombrafam** [comment]
FYI, it seems that the project is not actively maintained anymore see:
https://github.com/gnocchixyz/gnocchi/pull/1047#issuecomment-537051598

**Comment by cpl** [comment]
Cheers @sombrafam, I'll open this as an issue so other can see it faster :)

**Comment by chungg** [comment]
you can probably switch it to readthedocs to host it. it'll fix the versioning issue we had too. currently don't have time to do this though.

**Comment by jd** [comment]
The problem is that our docs are built with a postgresql and other stuff running behind to generate the HTTP request sample. RTD is unable to do that.

**Comment by Smiliebg** [comment]
For what it's worth, you can add following in your hosts file

8.43.85.232	gnocchi.xyz

This should work at least for as long as web hosting subscription is not terminated.

**Comment by ki4rbc** [comment]
Still no response from the [gnocchi website](https://gnocchi.xyz/)

**Comment by noonedeadpunk** [comment]
Folks, for whom docs are required, I've built them and placed on my small VM:
https://gnocchi.nodead.net/

Hope this will help someone :)

**Comment by erickonradmiller** [comment]
Has anyone tried to acquire the gnocchi.xyz domain?  We would be happy to pay for the account it is associated with, and migrate the site to our systems.

The WHOIS information is below.  It seems like the domain should be available soon since it expired 2 months ago and is in pendingDelete status.

---Domain Name: GNOCCHI.XYZ
Registry Domain ID: D10488785-CNIC
Registrar WHOIS Server: whois.gandi.net
Registrar URL: http://www.gandi.net/
Updated Date: 2019-11-13T13:04:28.0Z
Creation Date: 2015-09-29T18:49:32.0Z
Registry Expiry Date: 2019-09-29T23:59:59.0Z
Registrar: Gandi SAS
Registrar IANA ID: 81
Domain Status: pendingDelete https://icann.org/epp#pendingDelete
Domain Status: serverHold https://icann.org/epp#serverHold
Domain Status: serverTransferProhibited https://icann.org/epp#serverTransferProhibited
Domain Status: clientHold https://icann.org/epp#clientHold
Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
Domain Status: redemptionPeriod https://icann.org/epp#redemptionPeriod

**Comment by lukapeschke** [comment]
The documentation is available on https://gnocchi.osci.io/ since https://github.com/gnocchixyz/gnocchi/commit/4b670458e9a717ec325aa6bd725a1484b9346993 . Should this be closed ?

**Comment by jd** [comment]
Indeed.

**Comment by eldondev** [comment]
@jd I registered this domain, if you're interested in having it back in any real capacity, let me know. Otherwise I will probably just set up a redirect.

**Comment by jd** [comment]
@eldondev chat with @MichaelEischer that wanted to get it back, he's hosting the docs.

**Comment by MichaelEischer** [comment]
@jd I'm actually not involved in hosting the docs.
The intent of the bug report was to have an official website available, which is now the case again. The new url is fine for me.

**Comment by jd** [comment]
Sorry, I meant @mscherer.

**Comment by mscherer** [comment]
If people can add a CNAME to gnocchi.osci.io, that would be great. When we discussed with jd, the domain was parked and not worth the hassle to get it back under RH control (especially since domain stuff do involve using a specific registrar and "big corp process"). But activating the vhost is pretty fast and trivial.
