### ISSUE TITLE
Transform API

### ISSUE THREAD

**Issue by jd** [gnocchixyz/gnocchi#393]
The new transform API introduced in master after 4.0 is using a custom language based on things like:

`transform=absolute:negative`

passed in the query arguments.

We have another way smaller API already that is used to search metrics, passed as a body JSON on `post` and that looks like:

```
{"+": {"-": 5}}
```

So it could looks like:

```
{"-": "abs"}
```
In such a case. Math support would be easy.

The purpose of this bug is to discuss this before releasing the next milestone and be sure we expose a consistent API.

**Comment by jd** [comment]
@gnocchixyz/devs We did not make much progress here on this discussion. What do you guys think? Any lead?

**Comment by chungg** [comment]
i'm pretty sure @sileht said he had something yesterday.

i don't have a suggestion but tbh, i don't see how the json is clearer than writing the equation. math is math. maybe the problem i see with current transform is that it's hard to encode it for url.

**Comment by jd** [comment]
Yeah I think it's too complicated in a URL, especially if you go for mixing transform of math and also absolute or the like. :/

**Comment by sileht** [comment]
I have started the write some code for the jd_ json version, but I don't really like it.

Maybe we should just expose the pydata-numexpr format through the API in a POST:

```
{"transformations": [
  {"resample": "60"},
  {"math": "abs(sin(value * 3) / 2)" }
]}
```
or maybe we should always resample before any math and just do

```
{
  "resample": "60",
  "math": "abs(sin(value * 3) / 2)"
}
```
(We can drop absolute and reverse, their become useless with pydata-numexpr)

What we currently can't do with our API:
* I want "log10(metricX / metricY * 5)"

For this use-case, I imagined something like that:

```
{
    "metrics": ["cpu_util", "memory"],
    "resource_type": "collectd",
    "resources": "host like 'db_cluster_%'",  # Or the equivalent JSON.
    "transformations": [
        {"resample": "60"},
        {"math": "cpu_util / memory  * 2)" }
    ],
    "aggregated": {"fill": 5, needed_overlap: 50, reaggregation: "sum"}
}
```

But I'm unsure about the output format, because we can produce different thing:
* if aggregated: {"aggregate": TS}
* if no aggregate and no math that mixes TS: 
  {
     "resource-id1": {"cpu_util": TS, "memory": TS}
     "resource-id2": {"cpu_util": TS, "memory": TS}
  }
* if no aggregate and math that mixes TS: 
  {
     "resource-id1": {"computed": TS}
     "resource-id2": {"computed": TS}
  }

The other question is where we host the rest endpoint, the API to get measures start the become weird, we have:

- POST /v1/search/metric (returns many metrics)
- GET /v1/batch/metric (returns many metrics)
- GET /v1/metric/metric-id/measures (returns one metric)
- GET /v1/resource/generic/metric-name/measures (returns one metric)
- GET/POST /v1/aggregation/metric (returns aggregated metrics)
- POST /v1/aggregation/resource/generic/metric (returns aggregated metrics)

Each endpoints have different capabilities around reaggregation/resample/transform/....

I have imagined that must cover all other use-cases:

- POST /v1/measures
- POST /v1/retrieve-measures
- POST /v1/your-better-idea-about-measures

This raise to me some questions:

* What the behavior in case of different archive policy for each metric
* My pseudo solution can't do math between metric of different resources:
   - is that useful ?
   - is cross aggregation sufficient for that ?
* How we detect if math mixes metrics or not.

**Comment by jd** [comment]
I think we should split the problems in different part:

1. Operations about metrics, in that case we should reasonate about metrics by their ids. How to get those ids in the first place is another issue.

2. How to get IDs of metrics based on resources. That's basically a search operations in resources.

3. We need to build 1. and 2. and connect them together.

**1. Operations about metrics**

Ok, I'm going in. I think we should do it in a functional-Lisp way:

```
[resample 60 [abs [sin [/ [* 3 value ] 2]]]
```

We just have to expose a set of (Numpy) function, parse the list and applies operators. This is straightforward. You can use `value` several times if needed.

As you say, maybe we should just create a generic endpoint like `POST /v1/aggregates/fetch` that would return the aggregates of (a) metric(s) following this new format.

```
POST /v1/aggregates/fetch

{
 "metrics": [metric_id1, metric_id2], # batch support
 "operations": [resample 60 [abs [sin [/ [* 3 value ] 2]]]
}
```

**2. How to get IDs of metrics from resources**
I think we already have 2. with the search API and its expressions.

```
{
  "like": {
    "host": "compute%"
  }
}
```

That gives you a list of resources. You just need to select metrics and their IDs then.

**3. How to plug 1 and 2 together**

We could have an endpoint combining operations. For example:

```
POST /v1/aggregates/search-and-fetch
{
 "search": {
    "like": {
      "host": "compute%"
    }
  }
 "metric_names": ["memory", "memory.usage"],
 "operations": [resample 60 [abs [sin [/ [* 3 value ] 2]]]
}
```

**4. Cross metric aggregation**

We could also export an aggregation across multiple metrics like we do with:

```
POST /v1/aggregates/search-and-fetch
{
 "search": {
    "like": {
      "host": "compute%"
    }
  }
 "operations": [aggregate mean memory.usage]
}
```

We can also add a `groupby` operation I imagine. Think of it as `search-and-operate` like `map-reduce`. :)

**Comment by sileht** [comment]
About lisp, it's a bit less readable, but not so much. And it's easier to implement. But if I want to use it in Grafana I can't ask the user to write json array. I honestly don't want to write a parser in JS.

About search I think we should allow the JSON and the string "host like compute%" (We already implement that everywhere).

I have the felling that "operations" should allow the same and implement an user readable format server side. That avoid to see different parser/syntax depending of the used client (grafana syntax vs gnocchiclient syntax vs <put your client here>). If the human readable parser is implemented server side, all clients have the same syntax.

To resume JSON/LISP array is better for "application", math like format is better for "user".

The rest of the API looks the same as mine but with better wording/naming, the idea is the same.

The only missing part (that was badly expressed in my previous comment) is how to do math like:
"cpu_util / memory" or "processes-idle-0 / ( process-zombie-0 + processes-idle-0 + processes-running-0) * 100"

maybe by using metric ids and metric names instead of value ?

POST /v1/aggregate/XXX work for me.

**Comment by jd** [comment]
Ok, it makes sense to me to have a human readable syntax we can use everywhere.

> maybe by using metric ids and metric names instead of value ?

If you mean instead of `value`, yeah I think it's a good way to go. You can use a generic `value` word when only talking about a single metric, but if you have multiple metric selected by a search before, using ids or names is the good way to go.

@sileht so can you recap how you see the big things in the end before jumping on a patch? :)

**Comment by chungg** [comment]
@sileht i imagine you can't use metric names since you could be aggregating two cpu_util metrics together (in theory). also, how does math work if series do not overlap 100%?

why can't we just apply it as a list like we currently do? it seems like like easiest thing to understand; it steps through each transform operation.

**Comment by sileht** [comment]
I'm currently checking if I can reuse `cross_metric.aggregated()`, so we will get the same protection/filling stuff to ensure we have all needed points to do the math.

Instead of passing `reaggregation`, I will pass `operations`.  The awesome @chungg new numpy code created a matrix 
 (named `values`) where each columns is one metrics (I will just track the metric names/id from where the timeseries come from).

Some math examples, where `values` columns are metric-id-1/cpu_util,  metric-id-2/memory, metric-id-3/cpu_util metric-id-4/memory, metric-id-5/foobar

* `[/ metric-id-1 metric-id-2 ]` --> `numpy.divide(values.T[0], values.T[1]) `
    index 0 is metric-id-1 and index 1 is metric-id-2

* `[/ [aggregate mean [metric-id-1 metric-id-2]] metric-3]` --> `numpy.divide(numpy.mean(values.T[[0,2]].T, axis=1), values.T[1]))` 

With names, we expected that we have the same number of each metric names.

* `[aggregate mean cpu_util]` --> `numpy.mean(values.T[[0,2]].T, axis=1))`
    0 and 2 indexes are selected because their are cpu_util metrics

* `[* [+ cpu_util memory_usage] memory_usage] ` --> `numpy.multiply(numpy.add(values.T[[0,2]].T, values.T[[1,3]].T), values.T[[1,3]].T)`
    
* `[aggregate mean [+ cpu_util memory_usage]]` --> `numpy.mean((numpy.add(values.T[[0,2]].T, values.T[[1,3]].T), axis=1)`

And if `value` is used, we do the math on all metrics

* `[+ 3 value]`  --> `numpy.add(3, values)`

* `[aggregate mean value]` --> `numpy.mean(values, axis=1))`

**Comment by jd** [comment]
This looks really neat. Is `[+ 3 value]` a syntax you see there and is it good enough for grafana, or we need to add a layer above?

**Comment by sileht** [comment]
if `operations` is a string instead of a the pile python list structure I plan to convert it with this:
```
# import pyparsing as pp
# inputdata = '(/ (+ (2 (aggregate mean value))) 6)'
# print(pp.OneOrMore(pp.nestedExpr()).parseString(inputdata))
[['/', ['+', ['2', ['aggregate', 'mean', 'value']]], '6']]
```
Then I validate the resulting list of list with voluptuous.

**Comment by jd** [comment]
:+1:

**Comment by chungg** [comment]
> new numpy code created a matrix (named values) where each columns is one metrics (I will just track the metric names/id from where the timeseries come from).

that's exactly it :)

i'd prefer it to be standard math, but this syntax seems like an ok compromise and easier to parse.

does this mean we're going to deprecate reaggregation param since we could effectively do same thing with this syntax?

**Comment by sileht** [comment]
I have started the work here: #419 

Some notable change to make parser clearer about what metrics we aggregate:

* `value` become `[metric, all]`
*  `[metric-id-1 metric-id-2]` become `[metric [[metric-id-1 mean] [metric-id-2 mean]]]`
* `[* metric-id-1 2]` become `[* [metric metric-id-1 max] 2]`

This allow to make math between different aggregation of a metric like deltaing min/max:
```
POST /v1/aggregates/fetch
{
 "metrics": [[metric_id1, min], [metric_id1, max]],
 "operations": "(- (metric metric_id1 max) (metric metric_id1 min))"
}
```

@gordc, with my change, the /aggregates API looks like a more generic version of the cross_metric API.

**Comment by jd** [comment]
> * [metric-id-1 metric-id-2] become [metric [[metric-id-1 mean] [metric-id-2 mean]]]

Does that need to include the granularity, or is it global to the context of the request?

**Comment by jd** [comment]
@Asu4ni I know you're full on taxonomy, if you want to check this thread ;)

**Comment by sileht** [comment]
@jd Granularity stay global because to do the math/aggregation all timeseries must have the same size.

**Comment by sileht** [comment]
@jd Or if we laos add granularity, we can take the most accurate for initial timestamps base. Add use need_percent_of_overall= or fill=, to reject or fill missing points.

**Comment by sileht** [comment]
(Just thinking out of loud) Another input format to describe metrics could be :

```
POST /v1/aggregates/fetch
{
 "metrics": {"my name of m1": [metric_id1, min], "my_name_for_m2": [metric_id1, max]},
 "operations": "(- (metric 'my name of m1') (metric 'my_name_for_m2'))"
}
```

**Comment by jd** [comment]
> This format would also help to name resulting timeseries.

Well only if you add support for that too, no?

Otherwise that sounds like an `AS` operator so it makes sense to me. :)

**Comment by sileht** [comment]
> > This format would also help to name resulting timeseries.
>
> Well only if you add support for that too, no?

Not sure I got the question, so here an example of the API  returns:

My current patchset already returns different formats depending of the operations done.

* Operations like `(- (metric metric1 mean) (metric metric2 mean))` or `(aggregates mean (metric all))`, aggregates timeseries, so we return:

```
{"aggregated": [
   timestamp, granularity, value
   timestamp, granularity, value
   timestamp, granularity, value
   ...
]}
```
* Operations like `(* 2 ((metric metric1 mean) (metric metric2 mean)))` or `(* 2 (metric all))`, does not aggregates timeseries, so we return:

```
{"metric1_mean": [
   timestamp, granularity, value
   timestamp, granularity, value
   timestamp, granularity, value
   ...
],
"metric2_mean": [
   timestamp, granularity, value
   timestamp, granularity, value
   timestamp, granularity, value
   ...
]}
```
Here I have hardcoded the resulting name "%s_%s" % (metric-id, aggregation_method). So if instead we name used metrics, we can reuse this name for the output instead of hardcoding this.

**Comment by jd** [comment]
> Here I have hardcoded the resulting name "%s_%s" % (metric-id, aggregation_method). 

Yeah, that was my question. So your plan is to hardcode the name based on the names given as input. Sounds cool, but I imagined we would also allow to give a random to output:

```
POST /v1/aggregates/fetch
{
 "metrics": {"my name of m1": [metric_id1, min], "my_name_for_m2": [metric_id1, max]},
 "operations": "(as (- (metric 'my name of m1') (metric 'my_name_for_m2')) 'foobaz'"
}
```
```
{"foobaz": [
   timestamp, granularity, value
   timestamp, granularity, value
   timestamp, granularity, value
   ...
]}
```

**Comment by jd** [comment]
Another point:

If the language really looks like a Lispy AST, i.e., `(- (metric 'my name of m1') (metric 'my_name_for_m2'))`, it'd be great to support directly JSON syntax as well, e.g., `["-",  ["metric" "'my name of m1'"], ["metric" "'my_name_for_m2'"]]`.

Not sure it's a big deal to have since the `()` version might be parsed as an AST that would give lists anyway. But for code generation it might be simpler to generate code, serialize it a JSON, than writing strings. Whereas using `()` might be easier for UI like a CLI or Graphana.

**Comment by sileht** [comment]
`operations` already take both formats, I convert the Listpy AST string into the JSON syntax, because it's easier to parse the pile of list with voluptuous and to evaluate the nodes tree to compute aggregates:
https://github.com/gnocchixyz/gnocchi/pull/419/commits/9aa75aba2e9bf1b20fad1e50dd3be640e8dc42d7#diff-9e63aeb8fdca3fdca0a029008d385ffbR99

**Comment by chungg** [comment]
curious, but what is 'all' in 

> (* 2 (metric all))

**Comment by sileht** [comment]
>> curious, but what is 'all' in
> 
> (* 2 (metric all))

`all` is a shortcut for all metrics previously listed in `metrics/metric_names`

**Comment by sileht** [comment]
What do you think if we remove `metric/metric_names` from the payload request and just use the list of "(metric XXX YYY)" we found in the `operations` ?

**Comment by jd** [comment]
@sileht That sounds like a good simplification yes.

**Comment by Asu4ni** [comment]
After reading the entire thread (exhausted...) , I combine the ideas here ane there and add some of mine.

#### single metric fetch
```
GET /v1/metric/<id>/aggregates
{
  "operations": [+ [* $ 3] 2]
}
```
'$' is the placeholder. It can be used multiple times.

#### batch metric fetch
```
GET /v1/batch/metrics/aggregates
{
 "metrics": [<metric_id1>, <metric_id2>]
 "operations": [resample [abs [sin [/ [* 3 $ ] 2] ] 60]
}
```
'$' is the placeholder. It can be used multiple times.

#### aggregate across metric
```
GET /v1/aggregation/metric
{
 "metrics": [<metric_id1>, <metric_id2>]
 "operations": [ + [ mean [max $1] [min $2] ] $1 ]
}
```
'$n' is the placeholder for the nth metric.

And another thing that bothers me for a while is: why do some endpoints use POST and some use GET when both of them fetch(get) aggregates back?

**Comment by sileht** [comment]
I like the $ thing too.

I would prefer GET with a body too, but not all http clients/proxy/waf/... handle that correctly, that why we prefer to avoid it.

That why we propose to put the new endpoints on a new location, POST /v1/aggregates/XXX.
I guess all other API endpoint/method to retrieve measures should be deprecated (at least the /v1/aggregation and the batch measures retrieval)

**Comment by jd** [comment]
>  batch measures retrieval

IIRC this has not been released yet. Should we rip the code out?

**Comment by chungg** [comment]
we didn't release the batch measures retrieval code yet? i did that so long ago.lol

i would prefer we remove the metrics attribute as well if possible unless we implement it the way @Asu4ni suggested with $1, $2, etc...

**Comment by jd** [comment]
> we didn't release the batch measures retrieval code yet? i did that so long ago.lol

No, it was merged a few days after.

> i would prefer we remove the metrics attribute as well if possible unless we implement it the way @Asu4ni suggested with $1, $2, etc...

What do you call "metric attribute"?

**Comment by chungg** [comment]
>  "metrics": {"my name of m1": [metric_id1, min], "my_name_for_m2": [metric_id1, max]},

this. i don't know, it just seems like there's a disconnect between the operation and what it's working on... or is the reason that it's easier to spot what you're working on?

**Comment by jd** [comment]
@gordc ah ok, sure, we're all in line then :)

**Comment by jd** [comment]
@gnocchixyz/devs what's left to solve here so we can close this bug?

**Comment by chungg** [comment]
my only concern is the unnecessary memory/cpu usage when doing  simple batch get... but that isn't related to api.

**Comment by m0zart89** [comment]
I don't want to create new issue and have similar problem. So I have 3 resource types: instance_network_interface(input.bytes, outgoing.bytes), host_network_interface(input.bytes, outgoing.bytes), account(input.bytes, outgoing.bytes).

The 'account' C is aggregating 'instance_network_interface' A and 'host_network_interface' B in current time (the list of aggregated resources is not permanent).
I have 'relations.yaml':
```yaml
---
- account_id: 839f3f03-5a0d-55a1-a50a-47a2a337b99a
  sources:
  - resource_id: 0f1a8f61-0294-56d8-961f-6dd10d6e70d7
    sign: true
  - resource_id: a52a8201-fdab-5910-a82f-10ca1215b917
    sign: true
```

How can i fetch metrics by resource_id and name and aggregate them ?

**Comment by jd** [comment]
@m0zart89 you really should create a new issue
