### ISSUE TITLE
need more explanation on Back Window

### ISSUE THREAD

**Issue by ramesh-chowdeshetty** [gnocchixyz/gnocchi#458]
I have created an archive policy as below

{
    "definition": [
        {
            "points": 3600,
            "timespan": "1:00:00",
            "granularity": "0:00:01"
        }
    ],
    "back_window": 2,
    "name": "max",
    "aggregation_methods": [
        "max",
        "min",
        "mean"
    ]
}

After that I have created a Matrix with above archive policy. Then i have inserted below measures into it.

[ 	
  	{
    "timestamp": "2017-09-18 12:46:40",
    "value": 43.2
  },
  {
    "timestamp": "2017-09-18 12:46:41",
    "value": 43.1
  },
  
  {
    "timestamp":"2017-09-18 12:46:42",
    "value": 12
  },
  {
    "timestamp": "2017-09-18 12:46:43",
    "value": 2
  },
  
   {
    "timestamp": "2017-09-18 12:46:44",
    "value": 2
  },
  
  
   {
    "timestamp": "2017-09-18 12:46:45",
    "value": 3
  }
 ]

Next time  have inserted a value which contains timestamp "timestamp": "2017-09-18 12:46:39". which means one second old to current data.

but when i get measures it is displaying all values except this old one like below

 
[ 	
  	{
    "timestamp": "2017-09-18 12:46:40",
    "value": 43.2
  },
  {
    "timestamp": "2017-09-18 12:46:41",
    "value": 43.1
  },
  
  {
    "timestamp":"2017-09-18 12:46:42",
    "value": 12
  },
  {
    "timestamp": "2017-09-18 12:46:43",
    "value": 2
  },
  
   {
    "timestamp": "2017-09-18 12:46:44",
    "value": 2
  },
  
  
   {
    "timestamp": "2017-09-18 12:46:45",
    "value": 3
  }
 ]

here timestamp 39 second is not there , what can be the cause, somebody help me

**Comment by chungg** [comment]
gnocchi only accepts data more recent than or within the granularity period of the latest datapoint.

in your example, you have a granularity of 1 second which means, after your initial data push, only data greater than or equal to '2017-09-18 12:46:45' is accepted.

in your case, you have set back_window=2 which means gnocchi will accept data more recent than or within the granularity period of the latest datapoint and also any datapoint within two granularity periods earlier than latest datapoint.

using your example again but taking back_window into consideration, after your initial data push, only data greater than or equal to '2017-09-18 12:46:43' is accepted. 2 seconds earlier than latest period.

if you had a granularity of 2 seconds, it would've be anything great than or equal to '2017-09-18 12:46:40' because your latest granularity period would've been  '2017-09-18 12:46:44' and 2*2s puts it to  '2017-09-18 12:46:40'
