### ISSUE TITLE
Incompatible change in aggregates API

### ISSUE THREAD

**Issue by sasvaritoni** [gnocchixyz/gnocchi#497]
branch: stable/4.1

Hi,

With this recent commit, a non-backward-compatible change was introduced in the output of the aggregates API:
https://github.com/gnocchixyz/gnocchi/commit/e100051759c1182247d78787cb1d39b2e0a66887

Can this new format be considered as "final" (I mean in scope of the next release) ?
Are you planning to introduce a new /v2 API for this when it is released in 4.1.1 release?
I think this would be needed in case of such changes, otherwise how can a client know which output format to expect.

Do you have any plans on which Gnocchi version (and thus which version of the aggregates API) will be supported in any forthcoming RHOP version?
4.1, or 4.1.1, or potentially both?

Thanks,

Antal Sasvari
Software Developer
Ericsson Hungary Ltd.

**Comment by jd** [comment]
Hi Antal,

This patch in 4.1.1 is an **exceptional** fix that has been pushed because the first version of this API, released with 4.1.0, was not correctly usable without this change. It definitely breaks the API, strictly, speaking, but since that was released with 4.1.0 and has been available for just a few days before we emit this fix, we decided it was an adequate trade-off. If that is a big issue, it still possible to mitigate that by having the 2 versions, but we did not think it was worth it.

As for RHOP, I imagine you mean RH OSP. OSP12 ships the latest version of Gnocchi 4.0 (4.0.3 as of today). We do not know which version will OSP13 ship, but it will be at least 4.1.1.

**Comment by sasvaritoni** [comment]
This is great, thanks!
So then we can be sure that the 4.1.0 API will not be included in any RH OSP then,  only the 4.1.1 variant.

BR,
Antal

**Comment by jd** [comment]
> This is great, thanks! So then we can be sure that the 4.1.0 API will not be included in any RH OSP then, only the 4.1.1 variant.

Yes this is certain. :)

**Comment by chungg** [comment]
i feel like we should pull 4.1.0 from pypi. just to avoid confusion.

**Comment by jd** [comment]
@chungg good idea, done.
